### ISSUE TITLE
Create "Delightful Deployment" Engineering Plan

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/mailchimp-open-commerce-helm-chart#35]
Create a complete engineering plan for creating Delightful Deployments as defined in the spec

This plan should include:

1. An architecture diagram of all the pieces and how they fit together
1. Call outs for any pieces that @RickyHolland will not build himself (e.g. a webapp)
1. Grey screens of all the user inputs we need
1. The plan for the order it will be built including milestones
1. A plan for a series of blog posts talking about how it was built

**Comment by RickyHolland** [comment]
Engineering plan is being built in Miro to allow for collaboration and to improve communication (e.g. comments can be left for particular aspects).

Initial draft available at https://miro.com/app/board/uXjVOPxNKaY=/?invite_link_id=835548640511 (Note: access to Merchstack Miro Team required to access)

Currently includes a DD process flow chart, highlighting which components are likely to be frontend, backend and DevOps.

Also includes workflows of required GH Actions, bootstrap, CI and CD and their individual actions.
